project:
  type: website

website:
  title: "Manjot Singh"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Resume"
        file: resume.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Skills & Certifications"
        file: skills.qmd
      - text: "Contact"
        file: contact.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true
